spring:
  application:
    name: nishibi-bbs
  profiles:
    active: "dev"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${nishibi.db.host}:${nishibi.db.port}/${nishibi.db.name}"
    username: "${nishibi.db.username:nishibi}"
    password: "${nishibi.db.password:nishibi}"
nishibi:
  db:
    host: "${NISHIBI_DB_HOST:localhost}"
    port: "${NISHIBI_DB_PORT:5432}"
    name: "${NISHIBI_DB_NAME:nishibidb}"
    username: "${NISHIBI_DB_USERNAME:nishibi}"
    password: "${NISHIBI_DB_PASSWORD:nishibi}"
