spring:
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  mvc:
    log-request-details: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: true
logging:
  level:
    web: debug

nishibi:
  web:
    rate-limit:
      limit: 10
      window: 30
    cors:
      allowed-origins:
      - 'http://localhost:8080'
      - 'http://127.0.0.1:8080'
      # - 'https://bbs.misononoa.cc'
